### PR TITLE
Fixes ABU-874, ABU-787 & ABU-861

### PR DESCRIPTION
**Pull request by zenduo**
Fixes the 3 issues below:

https://adaptlearning.atlassian.net/browse/ABU-874
https://adaptlearning.atlassian.net/browse/ABU-787
https://adaptlearning.atlassian.net/browse/ABU-861

### CODE REVIEW

**Comment by moloko** [comment]
@zenduo would you mind also doing ```$ grunt dev ``` so that these changes are copied into the build also?

**Comment by zenduo** [comment]
Hi @moloko built and also added alt text for graphics throughout.

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
